### ISSUE TITLE
Tom radiator heat usage tab

### ISSUE THREAD

**Issue by nhassink** [kasteleman/com.plugwise.zigbee#13]
The heat usage (Dutch verwarmingsvraag) tab of the Tom radiator valve is not updating in homey 5.0.0

**Comment by kasteleman** [comment]
Are you familiar with running the app from a cli?
If so, could you please run it by using /run and report back some logging?

**Comment by nhassink** [comment]
Yes i can look into this

**Comment by kasteleman** [comment]
You can also contact me on slack

**Comment by nhassink** [comment]
Version 2.0.3 solves this issue for me. Thanks for the quick fix!
